//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lufthavn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rute
    {
        public int Id { get; set; }
        public string DepartedFrom { get; set; }
        public string DestinationFK { get; set; }
        public int AirplaneOnRuteFK { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual Airport Airport { get; set; }
    }
}
